require("kin.plugins")

require("kin.autocmds")
require("kin.cmp")
require("kin.colorscheme")
require("kin.keymaps")
require("kin.lsp")
require("kin.options")
require("kin.telescope")
require("kin.treesitter")
